import type { VocabularyWord } from "./types";

export const MOCK_VOCABULARY: VocabularyWord[] = [
  {
    id: "1",
    word: "invoice",
    phonetic: "/ˈɪn.vɔɪs/",
    partOfSpeech: "noun",
    meaning: "Hóa đơn",
    example:
      "Please send the invoice to the accounting department by Friday.",
    exampleTranslation:
      "Vui lòng gửi hóa đơn đến phòng kế toán trước thứ Sáu.",
    tags: ["Finance", "Office"],
    status: "mastered",
    isFavorite: true,
    note: "Common in Part 7 business correspondence.",
    addedAt: "2025-06-01T09:00:00Z",
    lastReviewedAt: "2025-06-10T14:00:00Z",
    reviewCount: 5,
  },
  {
    id: "2",
    word: "appointment",
    phonetic: "/əˈpɔɪnt.mənt/",
    partOfSpeech: "noun",
    meaning: "Cuộc hẹn, buổi gặp mặt",
    example:
      "Mr. Lee has an appointment with the client at 3 p.m.",
    exampleTranslation:
      "Ông Lee có cuộc hẹn với khách hàng lúc 3 giờ chiều.",
    tags: ["Office", "Meeting"],
    status: "mastered",
    isFavorite: false,
    note: "Often appears in listening Part 3 — scheduling dialogues.",
    addedAt: "2025-06-02T10:30:00Z",
    lastReviewedAt: "2025-06-09T11:00:00Z",
    reviewCount: 4,
  },
  {
    id: "3",
    word: "conference",
    phonetic: "/ˈkɑːn.fɚ.əns/",
    partOfSpeech: "noun",
    meaning: "Hội nghị, hội thảo",
    example:
      "The annual conference will be held at the Grand Hotel this year.",
    exampleTranslation:
      "Hội nghị thường niên sẽ được tổ chức tại khách sạn Grand năm nay.",
    tags: ["Meeting", "Business"],
    status: "learning",
    isFavorite: true,
    note: "Distinguish from 'meeting' — conference is larger and more formal.",
    addedAt: "2025-06-03T08:15:00Z",
    lastReviewedAt: "2025-06-08T16:30:00Z",
    reviewCount: 2,
  },
  {
    id: "4",
    word: "shipment",
    phonetic: "/ˈʃɪp.mənt/",
    partOfSpeech: "noun",
    meaning: "Lô hàng, sự vận chuyển",
    example:
      "The shipment of office supplies will arrive on Monday.",
    exampleTranslation:
      "Lô hàng văn phòng phẩm sẽ đến vào thứ Hai.",
    tags: ["Business", "Customer Service"],
    status: "learning",
    isFavorite: false,
    note: "Frequently used in Part 7 shipping notices.",
    addedAt: "2025-06-04T11:00:00Z",
    lastReviewedAt: "2025-06-05T09:00:00Z",
    reviewCount: 1,
  },
  {
    id: "5",
    word: "refund",
    phonetic: "/ˈriː.fʌnd/",
    partOfSpeech: "noun",
    meaning: "Tiền hoàn lại",
    example:
      "Customers may request a full refund within 30 days of purchase.",
    exampleTranslation:
      "Khách hàng có thể yêu cầu hoàn tiền đầy đủ trong vòng 30 ngày kể từ ngày mua.",
    tags: ["Customer Service", "Finance"],
    status: "learning",
    isFavorite: false,
    note: "Can also be used as a verb: 'to refund'.",
    addedAt: "2025-06-05T14:20:00Z",
    reviewCount: 0,
  },
  {
    id: "6",
    word: "department",
    phonetic: "/dɪˈpɑːrt.mənt/",
    partOfSpeech: "noun",
    meaning: "Phòng ban, bộ phận",
    example:
      "The marketing department is preparing a new campaign.",
    exampleTranslation:
      "Phòng marketing đang chuẩn bị một chiến dịch mới.",
    tags: ["Office", "Business"],
    status: "mastered",
    isFavorite: false,
    addedAt: "2025-06-01T08:00:00Z",
    lastReviewedAt: "2025-06-10T10:00:00Z",
    reviewCount: 6,
  },
  {
    id: "7",
    word: "applicant",
    phonetic: "/ˈæp.lɪ.kənt/",
    partOfSpeech: "noun",
    meaning: "Ứng viên, người nộp đơn",
    example:
      "All applicants must submit their résumés before the deadline.",
    exampleTranslation:
      "Tất cả ứng viên phải nộp hồ sơ trước hạn chót.",
    tags: ["Office", "Business"],
    status: "learning",
    isFavorite: true,
    note: "Common in job advertisement reading passages.",
    addedAt: "2025-06-06T09:45:00Z",
    lastReviewedAt: "2025-06-07T08:00:00Z",
    reviewCount: 1,
  },
  {
    id: "8",
    word: "deadline",
    phonetic: "/ˈded.laɪn/",
    partOfSpeech: "noun",
    meaning: "Hạn chót, thời hạn cuối",
    example:
      "The deadline for submitting proposals is next Wednesday.",
    exampleTranslation:
      "Hạn chót nộp đề xuất là thứ Tư tuần tới.",
    tags: ["Office", "Email"],
    status: "mastered",
    isFavorite: false,
    addedAt: "2025-06-02T07:30:00Z",
    lastReviewedAt: "2025-06-11T15:00:00Z",
    reviewCount: 7,
  },
  {
    id: "9",
    word: "reservation",
    phonetic: "/ˌrez.ɚˈveɪ.ʃən/",
    partOfSpeech: "noun",
    meaning: "Sự đặt chỗ, đặt phòng",
    example:
      "I'd like to make a reservation for two at 7 p.m.",
    exampleTranslation:
      "Tôi muốn đặt bàn cho hai người lúc 7 giờ tối.",
    tags: ["Travel", "Customer Service"],
    status: "learning",
    isFavorite: false,
    note: "Very common in Part 3 restaurant/hotel dialogues.",
    addedAt: "2025-06-07T13:00:00Z",
    reviewCount: 0,
  },
  {
    id: "10",
    word: "maintenance",
    phonetic: "/ˈmeɪn.tən.əns/",
    partOfSpeech: "noun",
    meaning: "Sự bảo trì, bảo dưỡng",
    example:
      "Building maintenance will take place over the weekend.",
    exampleTranslation:
      "Việc bảo trì tòa nhà sẽ diễn ra vào cuối tuần.",
    tags: ["Office", "Business"],
    status: "learning",
    isFavorite: false,
    note: "Appears in facility notices and announcements.",
    addedAt: "2025-06-08T10:00:00Z",
    lastReviewedAt: "2025-06-09T10:00:00Z",
    reviewCount: 1,
  },
  {
    id: "11",
    word: "negotiate",
    phonetic: "/nɪˈɡoʊ.ʃi.eɪt/",
    partOfSpeech: "verb",
    meaning: "Thương lượng, đàm phán",
    example:
      "We need to negotiate a better price for the annual contract.",
    exampleTranslation:
      "Chúng ta cần đàm phán giá tốt hơn cho hợp đồng hàng năm.",
    tags: ["Contract", "Meeting"],
    status: "learning",
    isFavorite: true,
    note: "Appears often in Part 7 business passages.",
    addedAt: "2025-06-09T16:00:00Z",
    lastReviewedAt: "2025-06-10T08:00:00Z",
    reviewCount: 2,
  },
  {
    id: "12",
    word: "survey",
    phonetic: "/ˈsɝː.veɪ/",
    partOfSpeech: "noun",
    meaning: "Cuộc khảo sát",
    example:
      "Please complete the customer satisfaction survey by Friday.",
    exampleTranslation:
      "Vui lòng hoàn thành khảo sát mức độ hài lòng của khách hàng trước thứ Sáu.",
    tags: ["Customer Service", "Email"],
    status: "learning",
    isFavorite: false,
    note: "Can also be a verb meaning 'to conduct a survey'.",
    addedAt: "2025-06-10T11:30:00Z",
    lastReviewedAt: "2025-06-11T09:00:00Z",
    reviewCount: 1,
  },
  {
    id: "13",
    word: "itinerary",
    phonetic: "/aɪˈtɪn.ə.rer.i/",
    partOfSpeech: "noun",
    meaning: "Lịch trình, hành trình",
    example:
      "Your travel itinerary has been updated with the new flight details.",
    exampleTranslation:
      "Lịch trình di chuyển của bạn đã được cập nhật với thông tin chuyến bay mới.",
    tags: ["Travel", "Business"],
    status: "learning",
    isFavorite: false,
    note: "Frequently appears in Part 7 travel emails.",
    addedAt: "2025-06-11T08:00:00Z",
    reviewCount: 0,
  },
  {
    id: "14",
    word: "comply",
    phonetic: "/kəmˈplaɪ/",
    partOfSpeech: "verb",
    meaning: "Tuân thủ, tuân theo",
    example:
      "All employees must comply with the company's safety regulations.",
    exampleTranslation:
      "Tất cả nhân viên phải tuân thủ quy định an toàn của công ty.",
    tags: ["Contract", "Office"],
    status: "learning",
    isFavorite: false,
    note: "Usually followed by 'with'. Part 5 grammar item.",
    addedAt: "2025-06-11T14:00:00Z",
    lastReviewedAt: "2025-06-12T07:00:00Z",
    reviewCount: 1,
  },
  {
    id: "15",
    word: "reimburse",
    phonetic: "/ˌriː.ɪmˈbɝːs/",
    partOfSpeech: "verb",
    meaning: "Hoàn trả chi phí",
    example:
      "The company will reimburse you for all travel expenses.",
    exampleTranslation:
      "Công ty sẽ hoàn trả cho bạn tất cả chi phí đi lại.",
    tags: ["Finance", "Business"],
    status: "learning",
    isFavorite: false,
    note: "Related: reimbursement (n.).",
    addedAt: "2025-06-12T09:00:00Z",
    reviewCount: 0,
  },
];
